#!/bin/sh

THEME_URL="https://github.com/manilarome/lightdm-webkit2-theme-glorious/releases/download/v2.0.5/lightdm-webkit2-theme-glorious-2.0.5.tar.gz"
THEME_DST=/usr/share/lightdm-webkit/themes/glorious

if [ -d  "$THEME_DST" ]; then
    echo "Theme already installed... updating"
else
    mkdir -p "$THEME_DST"
fi


curl -L -s $THEME_URL | tar xvz -C "$THEME_DST"
