# User configuration sourced by interactive shells

# Anaconda
. /home/void/.miniconda3/etc/profile.d/conda.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/void/.local/lib/google-cloud-sdk/path.zsh.inc' ]; then . '/home/void/.local/lib/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/void/.local/lib/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/void/.local/lib/google-cloud-sdk/completion.zsh.inc'; fi

eval "$(direnv hook zsh)"

eval "$(uv generate-shell-completion zsh)"
eval "$(uvx --generate-shell-completion zsh)"

_uv_run_mod() {
    if [[ "$words[2]" == "run" && "$words[CURRENT]" != -* ]]; then
        _arguments '*:filename:_files'
    else
        _uv "$@"
    fi
}
compdef _uv_run_mod uv
