#!/bin/sh

PLUG_FILE=${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim

test -e $PLUG_FILE || curl -fLo $PLUG_FILE --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"