#!/bin/sh

THEME_URL="https://gitlab.com/perthshiretim/refind-metal-theme/-/archive/master/refind-metal-theme-master.tar.gz"
THEME_DST=/boot/efi/EFI/refind/themes/metal

if [ -d  $THEME_DST ]; then
    echo "Theme already installed... updating"
else
    mkdir -p $THEME_DST
fi

curl -L -s $THEME_URL | tar xvz -C $THEME_DST --strip-components=1
