#!/bin/sh

THEME_URL="https://gitlab.com/perthshiretim/refind-metal-theme/-/archive/master/refind-metal-theme-master.tar.gz"
THEME_DST=/boot/efi/EFI/refind/metal

if [ -d  $THEME_DST ]; then
    echo "Theme already installed... updating"
    rm -rf $THEME_DST
fi

curl -s $THEME_URL | tar xvz -C $THEME_DST
