#!/bin/sh

barname=$DESKTOP_SESSION$(hostname)

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

touch $barname
exec polybar $barname 2>&1