#!/bin/bash

barname=$DESKTOP_SESSION$(hostname)

while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

# TODO https://github.com/polybar/polybar/discussions/2697
# Wait for pulseaudio to be online

pstat=$(pgrep -u $UID -x pulseaudio | xargs --no-run-if-empty ps -o stat --no-headers fp)

if [ ${pstat:0:1} == "D" ]; then
    echo 'pulse not ready'
    exit 1
fi

echo 'pulse ready'

exec polybar $barname 2>&1
