config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  emacs_dir: "{{@@ env['HOME'] @@}}/.emacs.d"
actions:
  pre:
    pluginstall: actions/nvim/pluginstall
    doom-install: actions/emacs/doominstall
  vim-pluginstall: vim +PlugInstall +qall
  doom-sync: '{{@@ emacs_dir @@}}/bin/doom sync'
  ziminstall: actions/zsh/ziminstall
  starship-install: 'curl -fsSL https://starship.rs/install.sh | bash'
dotfiles:
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    actions:
    - ziminstall
    - starship-install
    cmpignore:
    - '*.zwc'
    - '*.old'
    instignore:
    - '*.zwc'
    - '*.old'
    upignore:
    - '*.zwc'
    - '*.old'
  d_doom:
    src: config/doom
    dst: ~/.config/doom
    actions:
    - doom-install
    - doom-sync
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
    - vim-pluginstall
    - pluginstall
  f_profile:
    src: profile
    dst: ~/.profile
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_sv:
    src: config/sv
    dst: ~/.config/sv
    cmpignore:
    - '*supervise*'
    instignore:
    - '*supervise*'
    upignore:
    - '*supervise*'
  d_ubin:
    src: local/ubin
    dst: ~/.local/ubin
  d_dotbin:
    src: local/dotbin
    dst: ~/.local/dotbin
profiles:
  stealthlabs:
    dotfiles:
    - ALL
  thinkpad:
    dotfiles:
    - ALL
