config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  emacs_dir: "{{@@ env['HOME'] @@}}/.config/emacs"
actions:
  pre:
    doom-install: actions/emacs/doominstall
    void-bootstrap: actions/void/bootstrap
    pyenv-install: actions/python/pyenvinstall
  vim-pluginstall: vim +PlugInstall +qall
  doom-sync: '{{@@ emacs_dir @@}}/bin/doom sync'
  ziminstall: actions/zsh/ziminstall
  starship-install: curl -fsSL https://starship.rs/install.sh | bash
  tpminstall: actions/tmux/tpminstall
dotfiles:
  00_d_void:
    src:
    dst:
    actions:
    - void-bootstrap
  01_d_python:
    src:
    dst:
    actions:
    - pyenv-install
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    actions:
    - ziminstall
    - starship-install
    cmpignore:
    - '*.zwc'
    - '*.old'
    instignore:
    - '*.zwc'
    - '*.old'
    upignore:
    - '*.zwc'
    - '*.old'
  d_doom:
    src: config/doom
    dst: ~/.config/doom
    actions:
    - doom-install
    - doom-sync
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_profile:
    src: profile
    dst: ~/.profile
  d_sv:
    src: config/sv
    dst: ~/.config/sv
    cmpignore:
    - '*supervise*'
    instignore:
    - '*supervise*'
    upignore:
    - '*supervise*'
  d_ubin:
    src: local/ubin
    dst: ~/.local/ubin
  d_dotbin:
    src: local/dotbin
    dst: ~/.local/dotbin
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_gtk-2.0:
    src: config/gtk-2.0
    dst: ~/.config/gtk-2.0
    chmod: '700'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    chmod: '700'
  d_npm:
    src: config/npm
    dst: ~/.config/npm
  d_wezterm:
    src: config/wezterm
    dst: ~/.config/wezterm
  d_niri:
    src: config/niri
    dst: ~/.config/niri
  d_xdg-desktop-portal:
    src: config/xdg-desktop-portal
    dst: ~/.config/xdg-desktop-portal
  d_zellij:
    src: config/zellij
    dst: ~/.config/zellij
  d_pipewire:
    src: config/pipewire
    dst: ~/.config/pipewire
  d_gtklock:
    src: config/gtklock
    dst: ~/.config/gtklock
  d_nwg-look:
    src: config/nwg-look
    dst: ~/.config/nwg-look
  d_waypaper:
    src: config/waypaper
    dst: ~/.config/waypaper
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
profiles:
  stealthlabs:
    dotfiles:
    - ALL
    - d_wezterm
    - d_niri
    - d_xdg-desktop-portal
    - d_zellij
    - d_pipewire
    - d_gtklock
    - d_nwg-look
    - d_waypaper
    - d_waybar
  thinkpad:
    dotfiles:
    - ALL
