#!/bin/sh

pgrep -u "$USER" -fx "runsvdir -P $XDG_SERVICE_DIR .*" >/dev/null ||
  runsvdir -P "$XDG_SERVICE_DIR" 'log:.................................................................................................................' &
