# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[λ](bold green)"     # No spaces allowed between prompt and color
error_symbol = "[λ](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[python]
symbol = " "

[conda]
symbol = " "
